document.writeln("<select>");
document.writeln("               <option>0</option>");
document.writeln("               <option>1</option>");
document.writeln("               <option>2</option>");
document.writeln("               <option>3</option>");
document.writeln("               <option>4</option>");
document.writeln("               <option>5</option>");
document.writeln("               <option>6</option>");
document.writeln("               <option>7</option>");
document.writeln("               <option>8</option>");
document.writeln("               <option>9</option>");
document.writeln("               <option>10</option>");
document.writeln("           </select>");